FROM node:18-alpine

WORKDIR /app

# Copiar apenas o necessário para instalar dependências
COPY package*.json ./
COPY . .

# Instalar dependências incluindo Vite
RUN npm install --include=dev

EXPOSE 5173

CMD ["npm", "run", "dev"]