version: '3.8'

services:
  household-expenses:
    build: .
    ports:
      - "3000:4173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: household-expenses-app

  # Development service (optional)
  household-expenses-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    container_name: household-expenses-dev