FROM node:18-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Adicione esta linha para verificar a estrutura do projeto
RUN ls -la

# Para desenvolvimento, use o comando de dev diretamente
EXPOSE 5173
CMD ["npm", "run", "dev"]