FROM node:18-alpine

WORKDIR /app

# Copiar apenas o necessário para instalar dependências
COPY package*.json ./
COPY src/ ./src
COPY index.html .

# Instalar dependências incluindo Vite
RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev"]