version: '3.8'

services:
  financial-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - financial-network

networks:
  financial-network:
    driver: bridge