name: Lint

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t contas-frontend -f Dockerfile.frontend .

      - name: Run npm lint in Docker
        run: docker run contas-frontend npm run lint

      - name: Run TypeScript type check in Docker
        run: docker run contas-frontend npx tsc --noEmit

      - name: Run npm audit in Docker
        run: docker run contas-frontend npm audit
        continue-on-error: true

      - name: Run frontend tests in Docker
        run: docker run contas-frontend npm run test-frontend
