# .github/workflows/run-gemini-from-issue.yml
name: "IA-Driven Development Workflow"

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  ia_driven_task:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'ia-driven')

    steps:
      - name: "🔄 Checkout da branch base"
        uses: actions/checkout@v4
        with:
          ref: 'feature/ia'
          fetch-depth: 0

      - name: "📦 Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: "🔧 Configurar Git"
        run: |
          git config user.name "Gemini-CLI Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

      - name: "📁 Validar template base"
        run: |
          if [ ! -s ia/templates/001-general.md ]; then
            echo "❌ Template 'ia/templates/001-general.md' está ausente ou vazio."; exit 1;
          fi

      - name: "🌱 Criar branch e gerar plano de ação"
        id: prepare_branch
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME="ia/driven-$TIMESTAMP"
          PLAN_FILE_PATH="ia/templates/$TIMESTAMP.md"
          
          git checkout -b $BRANCH_NAME

          TASK_DESCRIPTION="${{ github.event.issue.body }}"
          TEMPLATE_CONTENT=$(cat ia/templates/001-general.md)

          PLAN_CONTENT="# 🧠 Plano de Ação Gerado por IA\n\n## Tarefa\n$TASK_DESCRIPTION\n\n## Etapas Sugeridas\n\n${TEMPLATE_CONTENT//<DESCRICAO_AQUI_CHANGE_ME>/$TASK_DESCRIPTION}"
          PLAN_CONTENT+="\n\nPor favor, implemente esta tarefa agora, sem pedir confirmação. Faça as alterações diretamente no código e comite na branch \`$BRANCH_NAME\`."

          echo "$PLAN_CONTENT" > "$PLAN_FILE_PATH"

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "plan_file_path=$PLAN_FILE_PATH" >> $GITHUB_OUTPUT
          echo "plan_content<<EOF" >> $GITHUB_OUTPUT
          echo "$PLAN_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: "🧠 Executar Gemini-CLI com o plano de ação"
        id: gemini_run
        env:
          GEMINI_PROMPT: "${{ steps.prepare_branch.outputs.plan_content }}"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Executando Gemini-CLI com prompt:"
          echo "$GEMINI_PROMPT"
          RESULT=$(npx @google/gemini-cli <<< "$GEMINI_PROMPT")

          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$RESULT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: "💾 Commit e Push das alterações"
        run: |
          git add .

          if git diff --staged --quiet; then
            echo "ℹ️ Nenhuma alteração de código detectada. Comitando apenas plano de ação."
            git commit -m "docs(ia): plano de ação da issue #${{ github.event.issue.number }}" -m "Issue: ${{ github.event.issue.html_url }}" || true
          else
            echo "✅ Alterações detectadas. Comitando tudo."
            git commit -m "feat(ia): implementar tarefa da issue #${{ github.event.issue.number }}" -m "Issue: ${{ github.event.issue.html_url }}" || true
          fi

          git push origin ${{ steps.prepare_branch.outputs.branch_name }}

      - name: "📬 Criar Pull Request em modo draft"
        id: create_pr
        uses: actions/github-script@v7
        with:
          script: |
            const headBranch = "${{ steps.prepare_branch.outputs.branch_name }}";
            const baseBranch = "feature/ia";
            const issueTitle = "${{ github.event.issue.title }}";
            const issueNumber = context.issue.number;

            try {
              const pr = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[IA-DRIVEN] ${issueTitle}`,
                head: headBranch,
                base: baseBranch,
                body: `Este PR foi gerado automaticamente pela IA para resolver a issue #${issueNumber}.\n\n- **Plano de Ação**: [${{ steps.prepare_branch.outputs.plan_file_path }}](${context.payload.repository.html_url}/blob/${headBranch}/${{ steps.prepare_branch.outputs.plan_file_path }})\n- **Issue Original**: #${issueNumber}`,
                draft: true
              });
              console.log(`✅ Pull Request criado: ${pr.data.html_url}`);
              return pr.data;
            } catch (error) {
              console.error(`❌ Erro ao criar Pull Request: ${error.message}`);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `### ⚠️ Erro ao criar Pull Request\n\nNão foi possível criar o Pull Request da branch \`${headBranch}\` para \`${baseBranch}\`.\n\n**Motivo provável:** A branch \`${baseBranch}\` não existe. Por favor, crie-a e o Pull Request poderá ser aberto manualmente.`
              });
              return null;
            }

      - name: "🗣️ Postar resultado na issue"
        uses: actions/github-script@v7
        with:
          script: |
            const prResult = ${{ toJSON(steps.create_pr.outputs.result) }};
            const branchName = "${{ steps.prepare_branch.outputs.branch_name }}";
            const repoUrl = context.payload.repository.html_url;
            let prUrl = null;

            if (prResult && typeof prResult === 'object' && prResult.html_url) {
              prUrl = prResult.html_url;
            } else if (typeof prResult === 'string') {
              try {
                const parsed = JSON.parse(prResult);
                if (parsed && parsed.html_url) prUrl = parsed.html_url;
              } catch (e) {}
            }

            const output = prUrl
              ? `
              ### 🤖✨ Fluxo de Trabalho de IA Concluído
              
              Um Pull Request em modo draft foi criado com as alterações geradas pela IA.
              
              - **Pull Request**: [${{ github.event.issue.title }}](${prUrl})
              - **Branch**: [${branchName}](${repoUrl}/tree/${branchName})
              - **Plano de Ação**: [${{ steps.prepare_branch.outputs.plan_file_path }}](${repoUrl}/blob/${branchName}/${{ steps.prepare_branch.outputs.plan_file_path }})
              
              #### Resultado da Execução do Gemini-CLI:
              \`\`\`
              ${{ steps.gemini_run.outputs.result }}
              \`\`\`
              `
              : `
              ### 🤖⚠️ Fluxo de Trabalho Concluído com Aviso

              A branch **${branchName}** foi criada e as alterações foram aplicadas, mas **não foi possível criar o Pull Request** automaticamente.

              Verifique o log da Action. Provável motivo: a branch base \`feature/ia\` não existe.
              `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            });
